// ===== SKILLHUB DATA =====
// Two-sided hiring platform: Individuals ("Get Help") and Businesses ("Hire People")

// ---------- TASK CATEGORIES (Individual flow) ----------
export const TASK_CATEGORIES = [
  "Cleaning",
  "Plumbing",
  "Moving",
  "Painting",
  "Gardening",
  "Repair",
  "Caregiving",
  "Household Help",
  "Electrical",
  "Appliance Repair",
  "Cooking",
  "Laundry",
] as const;
export type TaskCategory = (typeof TASK_CATEGORIES)[number];

// ---------- WORKER SKILLS ----------
export const WORKER_SKILLS = [
  "House Cleaning",
  "Deep Cleaning",
  "Plumbing",
  "Electrical",
  "Painting",
  "Carpentry",
  "Moving",
  "Packing",
  "Gardening",
  "Cooking",
  "Caregiving",
  "Elderly Care",
  "Child Care",
  "Warehouse",
  "Forklift",
  "Kitchen",
  "Serving",
  "Housekeeping",
  "Laundry",
  "Security",
  "Driving",
  "Delivery",
  "Construction",
  "Masonry",
  "Welding",
  "Repair",
] as const;
export type WorkerSkill = (typeof WORKER_SKILLS)[number];

export const LANGUAGES = [
  "English",
  "Bengali",
  "Japanese",
  "Arabic",
  "Portuguese",
  "Hindi",
  "Thai",
  "Italian",
  "Dutch",
  "Spanish",
  "Mandarin",
  "French",
  "Tagalog",
  "Urdu",
] as const;

// ---------- WORKERS ----------
export interface Worker {
  id: string;
  name: string;
  avatar: string; // emoji
  city: string;
  country: string;
  distanceKm?: number;
  skills: WorkerSkill[];
  verifiedSkills: WorkerSkill[];
  humanVerified: boolean;
  rating: number;
  reviews: number;
  completedWork: number;
  expectedRate: number; // per hour in local currency
  currency: string;
  languages: string[];
  availableNow: boolean;
  nextAvailable?: string;
  bio: string;
  joinedYear: number;
  responseTime: string;
}

export const WORKERS: Worker[] = [
  {
    id: "w1",
    name: "Rahim Uddin",
    avatar: "👷",
    city: "Gazipur",
    country: "Bangladesh",
    distanceKm: 3.2,
    skills: ["Warehouse", "Forklift", "Packing", "Moving"],
    verifiedSkills: ["Warehouse", "Forklift"],
    humanVerified: true,
    rating: 4.9,
    reviews: 87,
    completedWork: 142,
    expectedRate: 280,
    currency: "৳",
    languages: ["Bengali", "English"],
    availableNow: true,
    bio: "10 years warehouse experience. Forklift certified. Strong, reliable, never late.",
    joinedYear: 2019,
    responseTime: "< 10 min",
  },
  {
    id: "w2",
    name: "Yuki Tanaka",
    avatar: "👩",
    city: "Shinjuku, Tokyo",
    country: "Japan",
    distanceKm: 1.1,
    skills: ["Housekeeping", "Laundry", "Cooking", "House Cleaning"],
    verifiedSkills: ["Housekeeping", "Cooking"],
    humanVerified: true,
    rating: 5.0,
    reviews: 214,
    completedWork: 389,
    expectedRate: 2200,
    currency: "¥",
    languages: ["Japanese", "English"],
    availableNow: true,
    bio: "Former hotel housekeeper. 15 years hospitality. Meticulous and discreet.",
    joinedYear: 2017,
    responseTime: "< 5 min",
  },
  {
    id: "w3",
    name: "Ahmed Hassan",
    avatar: "👨‍🔧",
    city: "Deira, Dubai",
    country: "UAE",
    distanceKm: 5.8,
    skills: ["Construction", "Masonry", "Painting", "Electrical"],
    verifiedSkills: ["Construction", "Electrical"],
    humanVerified: true,
    rating: 4.7,
    reviews: 156,
    completedWork: 203,
    expectedRate: 45,
    currency: "AED",
    languages: ["Arabic", "English", "Hindi"],
    availableNow: false,
    nextAvailable: "Tomorrow 07:00",
    bio: "12 years construction in UAE. Can handle any site job. Safety certified.",
    joinedYear: 2018,
    responseTime: "< 30 min",
  },
  {
    id: "w4",
    name: "Maria Silva",
    avatar: "👩‍🍳",
    city: "Alfama, Lisbon",
    country: "Portugal",
    distanceKm: 2.4,
    skills: ["Cooking", "House Cleaning", "Laundry", "Caregiving"],
    verifiedSkills: ["Cooking"],
    humanVerified: false,
    rating: 4.8,
    reviews: 92,
    completedWork: 156,
    expectedRate: 12,
    currency: "€",
    languages: ["Portuguese", "Spanish", "English"],
    availableNow: true,
    bio: "Home cook and housekeeper. Portuguese traditional cuisine specialist.",
    joinedYear: 2020,
    responseTime: "< 15 min",
  },
  {
    id: "w5",
    name: "Priya Sharma",
    avatar: "👩‍⚕️",
    city: "Andheri, Mumbai",
    country: "India",
    distanceKm: 4.5,
    skills: ["Caregiving", "Elderly Care", "House Cleaning", "Cooking"],
    verifiedSkills: ["Caregiving", "Elderly Care"],
    humanVerified: true,
    rating: 4.9,
    reviews: 178,
    completedWork: 245,
    expectedRate: 350,
    currency: "₹",
    languages: ["Hindi", "English", "Marathi"],
    availableNow: true,
    bio: "Certified caregiver. 8 years elderly care. First aid trained. Compassionate.",
    joinedYear: 2018,
    responseTime: "< 10 min",
  },
  {
    id: "w6",
    name: "João Santos",
    avatar: "🚚",
    city: "Vila Madalena, São Paulo",
    country: "Brazil",
    distanceKm: 6.2,
    skills: ["Driving", "Delivery", "Moving", "Packing"],
    verifiedSkills: ["Driving"],
    humanVerified: false,
    rating: 4.6,
    reviews: 64,
    completedWork: 98,
    expectedRate: 35,
    currency: "R$",
    languages: ["Portuguese", "Spanish"],
    availableNow: true,
    bio: "Licensed driver, own van. Fast and careful with fragile items.",
    joinedYear: 2021,
    responseTime: "< 20 min",
  },
  {
    id: "w7",
    name: "Fatima Al-Zahra",
    avatar: "🧹",
    city: "Maadi, Cairo",
    country: "Egypt",
    distanceKm: 2.8,
    skills: ["House Cleaning", "Deep Cleaning", "Laundry", "Cooking"],
    verifiedSkills: ["House Cleaning", "Deep Cleaning"],
    humanVerified: true,
    rating: 4.9,
    reviews: 203,
    completedWork: 312,
    expectedRate: 120,
    currency: "EGP",
    languages: ["Arabic", "English"],
    availableNow: true,
    bio: "Professional deep cleaning specialist. Eco-friendly products. 9 years experience.",
    joinedYear: 2017,
    responseTime: "< 10 min",
  },
  {
    id: "w8",
    name: "Chen Wei",
    avatar: "👨‍🍳",
    city: "Little India, Singapore",
    country: "Singapore",
    distanceKm: 3.7,
    skills: ["Cooking", "Kitchen", "House Cleaning"],
    verifiedSkills: ["Cooking", "Kitchen"],
    humanVerified: true,
    rating: 4.8,
    reviews: 145,
    completedWork: 198,
    expectedRate: 22,
    currency: "S$",
    languages: ["Mandarin", "English", "Malay"],
    availableNow: false,
    nextAvailable: "Today 18:00",
    bio: "Trained chef. Chinese and Southeast Asian cuisine. Hygiene certified.",
    joinedYear: 2019,
    responseTime: "< 15 min",
  },
  {
    id: "w9",
    name: "Kwame Asante",
    avatar: "🔧",
    city: "Osu, Accra",
    country: "Ghana",
    distanceKm: 1.9,
    skills: ["Plumbing", "Electrical", "Repair", "Painting"],
    verifiedSkills: ["Plumbing", "Electrical"],
    humanVerified: true,
    rating: 4.7,
    reviews: 89,
    completedWork: 134,
    expectedRate: 65,
    currency: "GHS",
    languages: ["English", "Twi"],
    availableNow: true,
    bio: "All-round handyman. Plumbing and electrical specialist. Same-day service.",
    joinedYear: 2020,
    responseTime: "< 10 min",
  },
  {
    id: "w10",
    name: "Sofia Rossi",
    avatar: "🍝",
    city: "Trastevere, Rome",
    country: "Italy",
    distanceKm: 4.1,
    skills: ["Cooking", "House Cleaning", "Caregiving"],
    verifiedSkills: ["Cooking"],
    humanVerified: false,
    rating: 4.9,
    reviews: 167,
    completedWork: 221,
    expectedRate: 18,
    currency: "€",
    languages: ["Italian", "English", "French"],
    availableNow: true,
    bio: "Roman home cook. Traditional pasta and seasonal menus. Also do light cleaning.",
    joinedYear: 2018,
    responseTime: "< 15 min",
  },
  {
    id: "w11",
    name: "Arjun Patel",
    avatar: "🧑‍🌾",
    city: "Satellite, Ahmedabad",
    country: "India",
    distanceKm: 7.3,
    skills: ["Gardening", "House Cleaning", "Repair"],
    verifiedSkills: ["Gardening"],
    humanVerified: false,
    rating: 4.5,
    reviews: 42,
    completedWork: 67,
    expectedRate: 250,
    currency: "₹",
    languages: ["Hindi", "Gujarati", "English"],
    availableNow: true,
    bio: "Gardener and groundskeeper. Organic methods. Tree trimming specialist.",
    joinedYear: 2022,
    responseTime: "< 30 min",
  },
  {
    id: "w12",
    name: "Linh Nguyen",
    avatar: "👩",
    city: "District 1, Ho Chi Minh",
    country: "Vietnam",
    distanceKm: 2.2,
    skills: ["House Cleaning", "Laundry", "Cooking", "Caregiving"],
    verifiedSkills: ["House Cleaning"],
    humanVerified: true,
    rating: 4.8,
    reviews: 134,
    completedWork: 189,
    expectedRate: 85000,
    currency: "₫",
    languages: ["Vietnamese", "English"],
    availableNow: true,
    bio: "Reliable housekeeper. Vietnamese and international cooking. Child care experienced.",
    joinedYear: 2019,
    responseTime: "< 10 min",
  },
];

// ---------- COMPANIES / BUSINESSES ----------
export interface Company {
  id: string;
  name: string;
  industry: string;
  city: string;
  country: string;
  logo: string; // emoji
  verified: boolean;
  locations: number;
  activeJobs: number;
  activeShifts: number;
  workerRating: number;
  paymentReliability: number;
  jobAccuracy: number;
  workEnvironment: number;
  communication: number;
  safety: number;
  responseRate: number;
  repeatWorkerRate: number;
  tagline: string;
  description: string;
  perks: string[];
  hue: number;
}

export const COMPANIES: Company[] = [
  {
    id: "c1",
    name: "Shinjuku Grand Hotel",
    industry: "Hospitality",
    city: "Shinjuku, Tokyo",
    country: "Japan",
    logo: "🏨",
    verified: true,
    locations: 1,
    activeJobs: 8,
    activeShifts: 24,
    workerRating: 4.8,
    paymentReliability: 5.0,
    jobAccuracy: 4.9,
    workEnvironment: 4.7,
    communication: 4.8,
    safety: 4.9,
    responseRate: 98,
    repeatWorkerRate: 87,
    tagline: "Luxury hotel seeking reliable housekeeping and kitchen staff",
    description: "5-star hotel in the heart of Shinjuku. We treat our temporary workers like family — on-time payment, clean break rooms, respectful management.",
    perks: ["On-time payment", "Free meals on shift", "Transport covered", "Uniform provided"],
    hue: 220,
  },
  {
    id: "c2",
    name: "Al Fardan Warehouse",
    industry: "Logistics",
    city: "Jebel Ali, Dubai",
    country: "UAE",
    logo: "📦",
    verified: true,
    locations: 3,
    activeJobs: 15,
    activeShifts: 42,
    workerRating: 4.6,
    paymentReliability: 4.9,
    jobAccuracy: 4.5,
    workEnvironment: 4.3,
    communication: 4.6,
    safety: 4.8,
    responseRate: 95,
    repeatWorkerRate: 72,
    tagline: "Fast-growing logistics hub — always need reliable hands",
    description: "Major warehouse and distribution center in Jebel Ali Free Zone. We hire crews regularly for seasonal peaks. AC facility, safety gear provided.",
    perks: ["AC facility", "Safety gear provided", "Weekly payment", "Overtime paid"],
    hue: 30,
  },
  {
    id: "c3",
    name: "Café Central",
    industry: "Restaurant",
    city: "Chiado, Lisbon",
    country: "Portugal",
    logo: "☕",
    verified: true,
    locations: 2,
    activeJobs: 4,
    activeShifts: 12,
    workerRating: 4.9,
    paymentReliability: 5.0,
    jobAccuracy: 5.0,
    workEnvironment: 4.9,
    communication: 4.9,
    safety: 4.8,
    responseRate: 100,
    repeatWorkerRate: 92,
    tagline: "Family-run café — we hire people we'd invite to dinner",
    description: "Historic café in Chiado since 1922. Small team, big heart. We pay cash on the day, feed you well, and treat you like family.",
    perks: ["Cash same day", "Free meals", "Tips shared", "Flexible hours"],
    hue: 15,
  },
  {
    id: "c4",
    name: "GreenLeaf Restaurant",
    industry: "Restaurant",
    city: "Sukhumvit, Bangkok",
    country: "Thailand",
    logo: "🌿",
    verified: true,
    locations: 1,
    activeJobs: 6,
    activeShifts: 18,
    workerRating: 4.7,
    paymentReliability: 4.8,
    jobAccuracy: 4.7,
    workEnvironment: 4.8,
    communication: 4.6,
    safety: 4.7,
    responseRate: 92,
    repeatWorkerRate: 78,
    tagline: "Plant-based restaurant looking for passionate kitchen crew",
    description: "Award-winning plant-based restaurant. We need reliable kitchen helpers, servers, and cleaners who care about food and people.",
    perks: ["Free meals", "Weekly pay", "Training provided", "Friendly team"],
    hue: 130,
  },
  {
    id: "c5",
    name: "Portside Logistics",
    industry: "Logistics",
    city: "Rotterdam",
    country: "Netherlands",
    logo: "🚢",
    verified: true,
    locations: 2,
    activeJobs: 22,
    activeShifts: 56,
    workerRating: 4.5,
    paymentReliability: 4.9,
    jobAccuracy: 4.4,
    workEnvironment: 4.3,
    communication: 4.5,
    safety: 4.9,
    responseRate: 96,
    repeatWorkerRate: 68,
    tagline: "Europe's largest port — steady work, fair pay",
    description: "Major logistics operator at Rotterdam port. Continuous need for warehouse workers, forklift operators, and loaders. Union rates, strict safety.",
    perks: ["Union rates", "Safety bonus", "Transport allowance", "Pension eligible"],
    hue: 200,
  },
  {
    id: "c6",
    name: "Bella Cucina",
    industry: "Restaurant",
    city: "Trastevere, Rome",
    country: "Italy",
    logo: "🍕",
    verified: true,
    locations: 1,
    activeJobs: 3,
    activeShifts: 9,
    workerRating: 4.8,
    paymentReliability: 5.0,
    jobAccuracy: 4.8,
    workEnvironment: 4.9,
    communication: 4.7,
    safety: 4.6,
    responseRate: 94,
    repeatWorkerRate: 85,
    tagline: "Authentic Roman trattoria — family atmosphere",
    description: "Traditional trattoria in Trastevere. We hire for kitchen, service, and cleaning. Good food, good people, good pay on time.",
    perks: ["Family meals", "Tips pooled", "Flexible shifts", "Cash payment"],
    hue: 5,
  },
  {
    id: "c7",
    name: "CareFirst Home Services",
    industry: "Care",
    city: "Didsbury, Manchester",
    country: "United Kingdom",
    logo: "🏥",
    verified: true,
    locations: 4,
    activeJobs: 18,
    activeShifts: 38,
    workerRating: 4.6,
    paymentReliability: 4.8,
    jobAccuracy: 4.5,
    workEnvironment: 4.6,
    communication: 4.7,
    safety: 4.8,
    responseRate: 91,
    repeatWorkerRate: 74,
    tagline: "Home care provider — compassionate caregivers wanted",
    description: "Leading home care provider in Greater Manchester. We need caring, reliable caregivers for elderly clients. DBS checked, full training.",
    perks: ["Mileage paid", "DBS covered", "Paid training", "Career progression"],
    hue: 170,
  },
  {
    id: "c8",
    name: "BuildPro Construction",
    industry: "Construction",
    city: "Vila Olímpia, São Paulo",
    country: "Brazil",
    logo: "🏗️",
    verified: true,
    locations: 6,
    activeJobs: 31,
    activeShifts: 78,
    workerRating: 4.4,
    paymentReliability: 4.7,
    jobAccuracy: 4.3,
    workEnvironment: 4.2,
    communication: 4.4,
    safety: 4.8,
    responseRate: 88,
    repeatWorkerRate: 65,
    tagline: "Major construction firm — always hiring skilled hands",
    description: "One of São Paulo's largest construction companies. Residential and commercial projects. We need masons, helpers, electricians, and general labor.",
    perks: ["Safety gear", "Transport voucher", "Meal allowance", "Weekly pay"],
    hue: 45,
  },
];

// ---------- INDIVIDUAL TASKS ----------
export interface Task {
  id: string;
  title: string;
  category: TaskCategory;
  description: string;
  country: string;
  city: string;
  area: string;
  date: string;
  time: string;
  budget: number;
  currency: string;
  duration: string;
  workersNeeded: number;
  specialRequirements: string[];
  postedHours: number;
  offersCount: number;
  status: "open" | "in-progress" | "completed";
  clientName: string;
}

export const SAMPLE_TASKS: Task[] = [
  {
    id: "t1",
    title: "Deep clean 2-bedroom apartment",
    category: "Cleaning",
    description: "Need a thorough deep clean of my apartment before moving out. Kitchen, bathrooms, floors, windows. Supplies provided.",
    country: "Japan",
    city: "Tokyo",
    area: "Shinjuku",
    date: "Tomorrow",
    time: "09:00",
    budget: 18000,
    currency: "¥",
    duration: "5-6 hours",
    workersNeeded: 1,
    specialRequirements: ["Bring own supplies", "Pet-friendly (1 cat)"],
    postedHours: 2,
    offersCount: 7,
    status: "open",
    clientName: "Kenji M.",
  },
  {
    id: "t2",
    title: "Fix leaking kitchen tap",
    category: "Plumbing",
    description: "Kitchen tap has been dripping for a week. Need someone to fix or replace the cartridge.",
    country: "Portugal",
    city: "Lisbon",
    area: "Alfama",
    date: "Today",
    time: "14:00",
    budget: 45,
    currency: "€",
    duration: "1-2 hours",
    workersNeeded: 1,
    specialRequirements: ["Bring tools"],
    postedHours: 1,
    offersCount: 4,
    status: "open",
    clientName: "Ana P.",
  },
  {
    id: "t3",
    title: "Help moving to new flat",
    category: "Moving",
    description: "Moving from 2nd floor walk-up to another 2nd floor, 1.5km away. Mostly boxes and furniture. Need strong helpers.",
    country: "Brazil",
    city: "São Paulo",
    area: "Vila Madalena",
    date: "Saturday",
    time: "08:00",
    budget: 280,
    currency: "R$",
    duration: "4-5 hours",
    workersNeeded: 3,
    specialRequirements: ["Own transport helpful", "Fragile items"],
    postedHours: 5,
    offersCount: 12,
    status: "open",
    clientName: "Lucas R.",
  },
  {
    id: "t4",
    title: "Paint living room walls",
    category: "Painting",
    description: "Living room 4x5m. Walls already prepped. Just need painting. White emulsion provided.",
    country: "United Kingdom",
    city: "Manchester",
    area: "Didsbury",
    date: "Next Monday",
    time: "10:00",
    budget: 120,
    currency: "£",
    duration: "6-7 hours",
    workersNeeded: 1,
    specialRequirements: ["Careful with floors", "Own brushes/rollers"],
    postedHours: 8,
    offersCount: 6,
    status: "open",
    clientName: "Emma T.",
  },
  {
    id: "t5",
    title: "Elderly care - 3 day shift",
    category: "Caregiving",
    description: "Need caregiver for my mother (78, mobile but needs help with meals and medication). 3 consecutive days.",
    country: "India",
    city: "Mumbai",
    area: "Andheri",
    date: "Starting Friday",
    time: "08:00",
    budget: 4500,
    currency: "₹",
    duration: "3 days (10h/day)",
    workersNeeded: 1,
    specialRequirements: ["Experience with elderly", "First aid trained", "Hindi speaking"],
    postedHours: 12,
    offersCount: 9,
    status: "open",
    clientName: "Rajesh K.",
  },
  {
    id: "t6",
    title: "Garden cleanup and mowing",
    category: "Gardening",
    description: "Backyard overgrown. Need mowing, weeding, hedge trimming. Medium size garden ~100sqm.",
    country: "Netherlands",
    city: "Rotterdam",
    area: "Delfshaven",
    date: "This weekend",
    time: "09:00",
    budget: 95,
    currency: "€",
    duration: "4-5 hours",
    workersNeeded: 1,
    specialRequirements: ["Bring mower if possible"],
    postedHours: 18,
    offersCount: 5,
    status: "open",
    clientName: "Jan V.",
  },
];

// ---------- BUSINESS JOBS ----------
export interface BusinessJob {
  id: string;
  companyId: string;
  type: "regular" | "shift" | "crew";
  role: string;
  location: string;
  pay: string;
  schedule: string;
  employment: "Full-time" | "Part-time" | "Contract";
  requirements: string[];
  experience: string;
  languages: string[];
  positions: number;
  postedHours: number;
  applicants: number;
  status: "active" | "paused" | "filled";
  // Shift-specific
  date?: string;
  startTime?: string;
  endTime?: string;
  hourlyRate?: number;
  currency?: string;
  uniform?: string;
  meal?: boolean;
  transport?: boolean;
}

export const BUSINESS_JOBS: BusinessJob[] = [
  {
    id: "bj1",
    companyId: "c1",
    type: "regular",
    role: "Housekeeping Staff",
    location: "Shinjuku, Tokyo",
    pay: "¥1,400/hour",
    schedule: "Flexible shifts, 6h minimum",
    employment: "Part-time",
    requirements: ["Housekeeping experience", "Japanese basic", "Reliable"],
    experience: "1+ year",
    languages: ["Japanese", "English"],
    positions: 5,
    postedHours: 24,
    applicants: 23,
    status: "active",
  },
  {
    id: "bj2",
    companyId: "c1",
    type: "shift",
    role: "Banquet Server",
    location: "Shinjuku, Tokyo",
    pay: "¥1,600/hour",
    schedule: "Single shift",
    employment: "Contract",
    requirements: ["Serving experience", "Presentable", "Punctual"],
    experience: "6+ months",
    languages: ["Japanese"],
    positions: 8,
    postedHours: 6,
    applicants: 14,
    status: "active",
    date: "Saturday, Dec 14",
    startTime: "17:00",
    endTime: "23:00",
    hourlyRate: 1600,
    currency: "¥",
    uniform: "Black suit, white shirt",
    meal: true,
    transport: true,
  },
  {
    id: "bj3",
    companyId: "c2",
    type: "crew",
    role: "Warehouse Loader",
    location: "Jebel Ali, Dubai",
    pay: "AED 35/hour",
    schedule: "Full day",
    employment: "Contract",
    requirements: ["Physical fitness", "Warehouse experience", "ID required"],
    experience: "Any",
    languages: ["English", "Arabic", "Hindi"],
    positions: 15,
    postedHours: 3,
    applicants: 38,
    status: "active",
    date: "Tomorrow",
    startTime: "08:00",
    endTime: "17:00",
    hourlyRate: 35,
    currency: "AED",
    uniform: "Safety vest provided",
    meal: true,
    transport: true,
  },
  {
    id: "bj4",
    companyId: "c3",
    type: "regular",
    role: "Barista",
    location: "Chiado, Lisbon",
    pay: "€10/hour + tips",
    schedule: "Morning or afternoon shifts",
    employment: "Part-time",
    requirements: ["Coffee experience", "Friendly", "Portuguese or English"],
    experience: "6+ months",
    languages: ["Portuguese", "English"],
    positions: 2,
    postedHours: 48,
    applicants: 18,
    status: "active",
  },
  {
    id: "bj5",
    companyId: "c4",
    type: "shift",
    role: "Kitchen Helper",
    location: "Sukhumvit, Bangkok",
    pay: "฿200/hour",
    schedule: "Single shift",
    employment: "Contract",
    requirements: ["Kitchen experience", "Hygiene aware"],
    experience: "Any",
    languages: ["Thai", "English"],
    positions: 3,
    postedHours: 12,
    applicants: 9,
    status: "active",
    date: "Friday",
    startTime: "16:00",
    endTime: "23:00",
    hourlyRate: 200,
    currency: "฿",
    meal: true,
    transport: false,
  },
  {
    id: "bj6",
    companyId: "c5",
    type: "regular",
    role: "Forklift Operator",
    location: "Rotterdam",
    pay: "€16/hour",
    schedule: "Day shift, Mon-Fri",
    employment: "Full-time",
    requirements: ["Forklift license", "Safety certified", "Dutch or English"],
    experience: "2+ years",
    languages: ["Dutch", "English"],
    positions: 4,
    postedHours: 72,
    applicants: 31,
    status: "active",
  },
  {
    id: "bj7",
    companyId: "c7",
    type: "regular",
    role: "Home Caregiver",
    location: "Didsbury, Manchester",
    pay: "£12.50/hour + mileage",
    schedule: "Flexible, 4-8h shifts",
    employment: "Part-time",
    requirements: ["DBS checked", "Care experience", "Driving license"],
    experience: "1+ year",
    languages: ["English"],
    positions: 8,
    postedHours: 96,
    applicants: 42,
    status: "active",
  },
  {
    id: "bj8",
    companyId: "c8",
    type: "crew",
    role: "Construction Helper",
    location: "Vila Olímpia, São Paulo",
    pay: "R$ 28/hour",
    schedule: "Full day",
    employment: "Contract",
    requirements: ["Physical fitness", "Construction experience helpful"],
    experience: "Any",
    languages: ["Portuguese"],
    positions: 12,
    postedHours: 8,
    applicants: 27,
    status: "active",
    date: "Tomorrow",
    startTime: "07:00",
    endTime: "17:00",
    hourlyRate: 28,
    currency: "R$",
    meal: true,
    transport: true,
  },
];

// ---------- COMPANY REVIEWS (from workers) ----------
export interface CompanyReview {
  id: string;
  companyId: string;
  workerName: string;
  workerAvatar: string;
  role: string;
  date: string;
  paymentReliability: number;
  jobAccuracy: number;
  workEnvironment: number;
  communication: number;
  safety: number;
  comment: string;
  verifiedWork: boolean;
  communityComments: number;
}

export const COMPANY_REVIEWS: CompanyReview[] = [
  {
    id: "r1",
    companyId: "c1",
    workerName: "Yuki T.",
    workerAvatar: "👩",
    role: "Housekeeping",
    date: "2 weeks ago",
    paymentReliability: 5,
    jobAccuracy: 5,
    workEnvironment: 5,
    communication: 5,
    safety: 5,
    comment: "Best hotel I've worked at as temp. Payment always on time, break room is clean, managers are respectful. They even gave me a holiday bonus last year.",
    verifiedWork: true,
    communityComments: 12,
  },
  {
    id: "r2",
    companyId: "c1",
    workerName: "Min-jun P.",
    workerAvatar: "👨",
    role: "Banquet Server",
    date: "1 month ago",
    paymentReliability: 5,
    jobAccuracy: 5,
    workEnvironment: 4,
    communication: 5,
    safety: 5,
    comment: "Did a banquet shift here. Got paid same day plus transport. Staff meal was excellent. Only minor thing — changing rooms get crowded during peak hours.",
    verifiedWork: true,
    communityComments: 8,
  },
  {
    id: "r3",
    companyId: "c3",
    workerName: "Maria S.",
    workerAvatar: "👩‍🍳",
    role: "Barista",
    date: "3 weeks ago",
    paymentReliability: 5,
    jobAccuracy: 5,
    workEnvironment: 5,
    communication: 5,
    safety: 5,
    comment: "Like working for family. Cash in hand every shift, free meals, and the tips are shared fairly. João (the owner) remembers everyone's name.",
    verifiedWork: true,
    communityComments: 23,
  },
  {
    id: "r4",
    companyId: "c2",
    workerName: "Ahmed H.",
    workerAvatar: "👨‍🔧",
    role: "Warehouse Loader",
    date: "1 week ago",
    paymentReliability: 5,
    jobAccuracy: 4,
    workEnvironment: 4,
    communication: 4,
    safety: 5,
    comment: "Good pay, weekly transfer on time. Job description matches reality — heavy lifting but AC facility. Safety gear is proper. Would work again.",
    verifiedWork: true,
    communityComments: 15,
  },
  {
    id: "r5",
    companyId: "c7",
    workerName: "Sarah B.",
    workerAvatar: "👩‍⚕️",
    role: "Home Caregiver",
    date: "2 months ago",
    paymentReliability: 5,
    jobAccuracy: 4,
    workEnvironment: 5,
    communication: 5,
    safety: 5,
    comment: "Genuine care company. They match you with clients you can actually help. Mileage paid properly, training is paid, and managers actually check in.",
    verifiedWork: true,
    communityComments: 31,
  },
];

// ---------- TICKER / MISC ----------
export const TICKER_ITEMS = [
  "Rahim in Gazipur just got hired — Warehouse Loader",
  "Yuki completed 389 jobs — 5.0 rating",
  "Shinjuku Grand Hotel posted 8 new roles",
  "Al Fardan needs 15 loaders tomorrow",
  "Café Central paying cash same-day",
  "24 verified workers available in Tokyo now",
  "Priya in Mumbai — Caregiver, 4.9★",
  "Portside Logistics — 56 shifts this week",
];

export function formatAgo(hours: number): string {
  if (hours < 1) return "just now";
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  if (days === 1) return "yesterday";
  if (days < 7) return `${days}d ago`;
  const weeks = Math.floor(days / 7);
  return `${weeks}w ago`;
}
