export const CATEGORIES = [
  "Warehouse",
  "Manufacturing",
  "Delivery",
  "Cleaning",
  "Construction",
  "Packaging",
] as const;
export type Category = (typeof CATEGORIES)[number];

export type WorkMode = "On-site";
export type JobType = "Full-time" | "Part-time" | "Contract";
export type JobLevel = "Entry" | "Experienced" | "Supervisor";

export interface Company {
  id: string;
  name: string;
  hue: number;
  shape: 0 | 1 | 2;
  rating: number;
  reviews: number;
  openRoles: number;
  tagline: string;
  hq: string;
  perks: string[];
}

export interface Job {
  id: string;
  title: string;
  company: string;
  companyId: string;
  category: Category;
  type: JobType;
  level: JobLevel;
  mode: WorkMode;
  location: string;
  salaryMin: number;
  salaryMax: number;
  postedHours: number;
  tags: string[];
  featured?: boolean;
  description: string;
  responsibilities: string[];
}

export const COMPANIES: Company[] = [
  {
    id: "aqua-pack",
    name: "AquaPack Industries",
    hue: 200,
    shape: 1,
    rating: 4.3,
    reviews: 89,
    openRoles: 18,
    tagline: "Water bag & bottle manufacturing since 2005.",
    hq: "Dhaka",
    perks: ["Free lunch", "Transport", "Overtime pay"],
  },
  {
    id: "mega-wh",
    name: "Mega Warehouse Co.",
    hue: 30,
    shape: 0,
    rating: 4.1,
    reviews: 156,
    openRoles: 42,
    tagline: "Largest storage & logistics hub in the region.",
    hq: "Gazipur",
    perks: ["Weekly pay", "Night shift bonus", "Free tea"],
  },
  {
    id: "swift-delivery",
    name: "Swift Delivery",
    hue: 140,
    shape: 2,
    rating: 4.5,
    reviews: 203,
    openRoles: 35,
    tagline: "Fastest local delivery service.",
    hq: "Dhaka",
    perks: ["Fuel allowance", "Phone bill", "Flexible hours"],
  },
  {
    id: "clean-pro",
    name: "CleanPro Services",
    hue: 170,
    shape: 1,
    rating: 4.0,
    reviews: 67,
    openRoles: 24,
    tagline: "Professional cleaning for offices & homes.",
    hq: "Mirpur",
    perks: ["Supplies provided", "Weekend off", "Uniform provided"],
  },
  {
    id: "build-right",
    name: "BuildRight Construction",
    hue: 20,
    shape: 0,
    rating: 4.2,
    reviews: 112,
    openRoles: 28,
    tagline: "Residential & commercial construction.",
    hq: "Uttara",
    perks: ["Safety gear", "Meal allowance", "Project bonus"],
  },
  {
    id: "fresh-pack",
    name: "FreshPack Foods",
    hue: 50,
    shape: 2,
    rating: 4.4,
    reviews: 78,
    openRoles: 15,
    tagline: "Food packaging & distribution.",
    hq: "Savar",
    perks: ["Free meals", "Health checkup", "Festival bonus"],
  },
  {
    id: "rapid-logistics",
    name: "Rapid Logistics",
    hue: 260,
    shape: 1,
    rating: 3.9,
    reviews: 94,
    openRoles: 31,
    tagline: "Cargo & freight transport solutions.",
    hq: "Narayanganj",
    perks: ["Driver allowance", "Loading bonus", "Insurance"],
  },
  {
    id: "green-clean",
    name: "GreenClean BD",
    hue: 120,
    shape: 0,
    rating: 4.6,
    reviews: 45,
    openRoles: 12,
    tagline: "Eco-friendly cleaning solutions.",
    hq: "Banani",
    perks: ["Eco products", "Training", "Tips allowed"],
  },
];

export const JOBS: Job[] = [
  {
    id: "j1",
    title: "Warehouse Loader",
    company: "Mega Warehouse Co.",
    companyId: "mega-wh",
    category: "Warehouse",
    type: "Full-time",
    level: "Entry",
    mode: "On-site",
    location: "Gazipur",
    salaryMin: 12000,
    salaryMax: 16000,
    postedHours: 2,
    tags: ["Heavy lifting", "Night shift", "Loading"],
    featured: true,
    description:
      "Loading and unloading goods from trucks. Must be physically fit and able to lift 25kg+ regularly. Previous warehouse experience preferred but not required.",
    responsibilities: [
      "Load and unload delivery trucks",
      "Stack and organize goods on shelves",
      "Check items against delivery notes",
      "Keep warehouse area clean and safe",
    ],
  },
  {
    id: "j2",
    title: "Water Bag Machine Operator",
    company: "AquaPack Industries",
    companyId: "aqua-pack",
    category: "Manufacturing",
    type: "Full-time",
    level: "Experienced",
    mode: "On-site",
    location: "Dhaka",
    salaryMin: 15000,
    salaryMax: 22000,
    postedHours: 5,
    tags: ["Machine operation", "Production line", "Plastic"],
    featured: true,
    description:
      "Operating water bag sealing and filling machines. Must have at least 1 year experience in a factory or manufacturing setup.",
    responsibilities: [
      "Operate water bag filling & sealing machines",
      "Monitor production quality",
      "Report machine issues to supervisor",
      "Maintain clean workstation",
    ],
  },
  {
    id: "j3",
    title: "Delivery Rider (Bike)",
    company: "Swift Delivery",
    companyId: "swift-delivery",
    category: "Delivery",
    type: "Full-time",
    level: "Entry",
    mode: "On-site",
    location: "Dhaka",
    salaryMin: 18000,
    salaryMax: 25000,
    postedHours: 1,
    tags: ["Motorcycle", "License required", "Daily pay option"],
    featured: true,
    description:
      "Delivering food and packages across Dhaka city. Must have a valid driving license and own motorcycle. Daily or weekly pay available.",
    responsibilities: [
      "Pick up and deliver orders on time",
      "Use mobile app for navigation",
      "Collect cash payments when needed",
      "Maintain vehicle in good condition",
    ],
  },
  {
    id: "j4",
    title: "Office Cleaner",
    company: "CleanPro Services",
    companyId: "clean-pro",
    category: "Cleaning",
    type: "Full-time",
    level: "Entry",
    mode: "On-site",
    location: "Mirpur",
    salaryMin: 10000,
    salaryMax: 14000,
    postedHours: 8,
    tags: ["Morning shift", "Supplies provided", "No experience needed"],
    description:
      "Cleaning offices and commercial spaces. All cleaning supplies and equipment provided. Training given for new workers.",
    responsibilities: [
      "Sweep, mop and vacuum floors",
      "Clean bathrooms and restock supplies",
      "Empty trash bins",
      "Wipe down desks and surfaces",
    ],
  },
  {
    id: "j5",
    title: "Construction Helper",
    company: "BuildRight Construction",
    companyId: "build-right",
    category: "Construction",
    type: "Full-time",
    level: "Entry",
    mode: "On-site",
    location: "Uttara",
    salaryMin: 14000,
    salaryMax: 18000,
    postedHours: 3,
    tags: ["Physical work", "Safety gear provided", "Meal included"],
    description:
      "Assisting masons and supervisors at construction sites. Must be able to work in outdoor conditions and lift heavy materials.",
    responsibilities: [
      "Carry cement, bricks and materials",
      "Mix concrete as directed",
      "Help masons with their work",
      "Clean and prepare work areas",
    ],
  },
  {
    id: "j6",
    title: "Food Packaging Worker",
    company: "FreshPack Foods",
    companyId: "fresh-pack",
    category: "Packaging",
    type: "Full-time",
    level: "Entry",
    mode: "On-site",
    location: "Savar",
    salaryMin: 11000,
    salaryMax: 15000,
    postedHours: 6,
    tags: ["Food safety", "Assembly line", "Hygiene required"],
    description:
      "Packing food items on the production line. Must follow hygiene rules and wear provided uniform and gloves.",
    responsibilities: [
      "Pack food items into containers",
      "Seal and label packages",
      "Check for quality issues",
      "Keep packaging area clean",
    ],
  },
  {
    id: "j7",
    title: "Warehouse Supervisor",
    company: "Mega Warehouse Co.",
    companyId: "mega-wh",
    category: "Warehouse",
    type: "Full-time",
    level: "Supervisor",
    mode: "On-site",
    location: "Gazipur",
    salaryMin: 25000,
    salaryMax: 35000,
    postedHours: 12,
    tags: ["Team management", "Inventory", "5+ years experience"],
    featured: true,
    description:
      "Managing a team of 15+ warehouse workers. Must have at least 5 years warehouse experience and ability to manage teams.",
    responsibilities: [
      "Supervise daily warehouse operations",
      "Manage worker schedules",
      "Track inventory levels",
      "Ensure safety compliance",
    ],
  },
  {
    id: "j8",
    title: "Truck Driver (Heavy)",
    company: "Rapid Logistics",
    companyId: "rapid-logistics",
    category: "Delivery",
    type: "Full-time",
    level: "Experienced",
    mode: "On-site",
    location: "Narayanganj",
    salaryMin: 22000,
    salaryMax: 30000,
    postedHours: 4,
    tags: ["Heavy license", "Long routes", "Overnight trips"],
    description:
      "Driving heavy trucks for cargo transport between cities. Must have heavy vehicle license and be willing to do overnight trips.",
    responsibilities: [
      "Drive trucks on assigned routes",
      "Load and secure cargo safely",
      "Complete delivery paperwork",
      "Perform basic vehicle checks",
    ],
  },
  {
    id: "j9",
    title: "House Cleaner (Part-time)",
    company: "GreenClean BD",
    companyId: "green-clean",
    category: "Cleaning",
    type: "Part-time",
    level: "Entry",
    mode: "On-site",
    location: "Banani",
    salaryMin: 6000,
    salaryMax: 9000,
    postedHours: 10,
    tags: ["Part-time", "Morning only", "Tips allowed"],
    description:
      "Cleaning residential apartments in Banani area. Part-time, morning shifts only. Eco-friendly products used.",
    responsibilities: [
      "Clean 2-3 apartments per day",
      "Use eco-friendly cleaning products",
      "Report maintenance issues",
      "Collect keys from office each morning",
    ],
  },
  {
    id: "j10",
    title: "Mason (Rajmistri)",
    company: "BuildRight Construction",
    companyId: "build-right",
    category: "Construction",
    type: "Full-time",
    level: "Experienced",
    mode: "On-site",
    location: "Uttara",
    salaryMin: 20000,
    salaryMax: 28000,
    postedHours: 7,
    tags: ["Brick work", "Plastering", "3+ years experience"],
    description:
      "Skilled mason for residential construction. Must have 3+ years experience in brick laying, plastering and basic finishing.",
    responsibilities: [
      "Lay bricks and blocks",
      "Apply plaster and finish walls",
      "Read basic construction plans",
      "Supervise helpers on site",
    ],
  },
  {
    id: "j11",
    title: "Water Bag Packing Worker",
    company: "AquaPack Industries",
    companyId: "aqua-pack",
    category: "Packaging",
    type: "Full-time",
    level: "Entry",
    mode: "On-site",
    location: "Dhaka",
    salaryMin: 10000,
    salaryMax: 13000,
    postedHours: 14,
    tags: ["Manual packing", "Standing work", "No experience needed"],
    description:
      "Packing finished water bags into bundles for delivery. Simple manual work, training provided on first day.",
    responsibilities: [
      "Pack water bags into bundles of 20",
      "Stack bundles on pallets",
      "Count and record quantities",
      "Keep work area tidy",
    ],
  },
  {
    id: "j12",
    title: "Delivery Helper",
    company: "Swift Delivery",
    companyId: "swift-delivery",
    category: "Delivery",
    type: "Part-time",
    level: "Entry",
    mode: "On-site",
    location: "Dhaka",
    salaryMin: 8000,
    salaryMax: 11000,
    postedHours: 9,
    tags: ["Loading help", "No license needed", "Evening shift"],
    description:
      "Helping delivery riders load packages onto bikes. Evening shift, 4pm to 10pm. Good for students.",
    responsibilities: [
      "Sort packages by area",
      "Load packages onto delivery bikes",
      "Scan packages with app",
      "Keep loading area organized",
    ],
  },
  {
    id: "j13",
    title: "Forklift Operator",
    company: "Mega Warehouse Co.",
    companyId: "mega-wh",
    category: "Warehouse",
    type: "Full-time",
    level: "Experienced",
    mode: "On-site",
    location: "Gazipur",
    salaryMin: 18000,
    salaryMax: 24000,
    postedHours: 18,
    tags: ["Forklift license", "Heavy machinery", "Safety conscious"],
    description:
      "Operating forklift to move pallets and heavy items in warehouse. Must have valid forklift operating certificate.",
    responsibilities: [
      "Operate forklift safely",
      "Move pallets to storage areas",
      "Load/unload trucks",
      "Perform daily machine checks",
    ],
  },
  {
    id: "j14",
    title: "Factory Machine Helper",
    company: "AquaPack Industries",
    companyId: "aqua-pack",
    category: "Manufacturing",
    type: "Full-time",
    level: "Entry",
    mode: "On-site",
    location: "Dhaka",
    salaryMin: 11000,
    salaryMax: 14000,
    postedHours: 20,
    tags: ["Factory floor", "Shift work", "Training provided"],
    description:
      "Assisting machine operators in the water bag factory. Entry level position with full training provided.",
    responsibilities: [
      "Supply raw materials to machines",
      "Remove finished products",
      "Clean machines at end of shift",
      "Follow safety procedures",
    ],
  },
  {
    id: "j15",
    title: "Cargo Loader",
    company: "Rapid Logistics",
    companyId: "rapid-logistics",
    category: "Warehouse",
    type: "Contract",
    level: "Entry",
    mode: "On-site",
    location: "Narayanganj",
    salaryMin: 13000,
    salaryMax: 17000,
    postedHours: 15,
    tags: ["Heavy lifting", "Dock work", "Contract 3 months"],
    description:
      "Loading cargo onto trucks at the Narayanganj dock. 3-month contract with possibility of permanent position.",
    responsibilities: [
      "Load cargo onto trucks",
      "Secure loads properly",
      "Work with crane operators",
      "Follow loading procedures",
    ],
  },
  {
    id: "j16",
    title: "Deep Cleaning Specialist",
    company: "CleanPro Services",
    companyId: "clean-pro",
    category: "Cleaning",
    type: "Full-time",
    level: "Experienced",
    mode: "On-site",
    location: "Mirpur",
    salaryMin: 14000,
    salaryMax: 19000,
    postedHours: 22,
    tags: ["Deep clean", "Chemical handling", "Experience needed"],
    description:
      "Performing deep cleaning of kitchens, bathrooms and commercial spaces. Must know how to handle cleaning chemicals safely.",
    responsibilities: [
      "Deep clean kitchens and bathrooms",
      "Handle cleaning chemicals safely",
      "Use specialized equipment",
      "Train junior cleaners",
    ],
  },
  {
    id: "j17",
    title: "Carton Box Maker",
    company: "FreshPack Foods",
    companyId: "fresh-pack",
    category: "Manufacturing",
    type: "Full-time",
    level: "Entry",
    mode: "On-site",
    location: "Savar",
    salaryMin: 10000,
    salaryMax: 14000,
    postedHours: 26,
    tags: ["Box folding", "Manual work", "Glue work"],
    description:
      "Making cardboard boxes by hand for food packaging. Simple repetitive work, good for people who like steady tasks.",
    responsibilities: [
      "Fold and glue cardboard boxes",
      "Stack finished boxes",
      "Count daily production",
      "Keep work area clean",
    ],
  },
  {
    id: "j18",
    title: "Site Safety Officer",
    company: "BuildRight Construction",
    companyId: "build-right",
    category: "Construction",
    type: "Full-time",
    level: "Supervisor",
    mode: "On-site",
    location: "Uttara",
    salaryMin: 28000,
    salaryMax: 38000,
    postedHours: 30,
    tags: ["Safety certification", "Supervision", "Reporting"],
    description:
      "Ensuring safety compliance on construction sites. Must have safety officer certification and 5+ years construction experience.",
    responsibilities: [
      "Inspect sites for safety hazards",
      "Train workers on safety",
      "Maintain safety records",
      "Report incidents to management",
    ],
  },
  {
    id: "j19",
    title: "Bottle Washing Worker",
    company: "AquaPack Industries",
    companyId: "aqua-pack",
    category: "Manufacturing",
    type: "Full-time",
    level: "Entry",
    mode: "On-site",
    location: "Dhaka",
    salaryMin: 9000,
    salaryMax: 12000,
    postedHours: 32,
    tags: ["Washing", "Standing work", "Wet environment"],
    description:
      "Washing and sanitizing water bottles before filling. Work involves standing and wet conditions all day.",
    responsibilities: [
      "Wash bottles by hand and machine",
      "Check bottles for damage",
      "Apply sanitizing solution",
      "Stack clean bottles for filling",
    ],
  },
  {
    id: "j20",
    title: "Evening Security Guard",
    company: "Mega Warehouse Co.",
    companyId: "mega-wh",
    category: "Warehouse",
    type: "Full-time",
    level: "Entry",
    mode: "On-site",
    location: "Gazipur",
    salaryMin: 12000,
    salaryMax: 15000,
    postedHours: 36,
    tags: ["Night shift", "Gate duty", "Patrol rounds"],
    description:
      "Night security for warehouse compound. Must be alert and able to do patrol rounds every hour.",
    responsibilities: [
      "Guard main gate at night",
      "Check ID of all visitors",
      "Do hourly patrol rounds",
      "Report any suspicious activity",
    ],
  },
  {
    id: "j21",
    title: "Parcel Sorter",
    company: "Swift Delivery",
    companyId: "swift-delivery",
    category: "Packaging",
    type: "Part-time",
    level: "Entry",
    mode: "On-site",
    location: "Dhaka",
    salaryMin: 7000,
    salaryMax: 10000,
    postedHours: 40,
    tags: ["Sorting", "Fast-paced", "Part-time available"],
    description:
      "Sorting parcels by delivery area at the main hub. Fast-paced environment, good pay for quick workers.",
    responsibilities: [
      "Sort parcels by area code",
      "Scan each parcel",
      "Place in correct bins",
      "Meet hourly targets",
    ],
  },
  {
    id: "j22",
    title: "Plumber Helper",
    company: "BuildRight Construction",
    companyId: "build-right",
    category: "Construction",
    type: "Full-time",
    level: "Entry",
    mode: "On-site",
    location: "Uttara",
    salaryMin: 13000,
    salaryMax: 17000,
    postedHours: 44,
    tags: ["Plumbing", "Helper role", "Learn trade"],
    description:
      "Helping plumbers on construction sites. Great opportunity to learn plumbing trade while earning.",
    responsibilities: [
      "Carry pipes and tools",
      "Help with pipe fitting",
      "Mix cement for pipe joints",
      "Clean up after work",
    ],
  },
];

export const TICKER_ITEMS: string[] = [
  "AquaPack — 18 open roles",
  "Mega Warehouse — 42 workers needed",
  "Swift Delivery — Hiring riders daily",
  "BuildRight — Site workers wanted",
  "CleanPro — Morning shift available",
  "FreshPack — Packaging line hiring",
  "Rapid Logistics — Drivers needed",
  "GreenClean — Part-time cleaners",
  "Daily wages available at select sites",
  "Free transport from major points",
];

export function formatAgo(hours: number): string {
  if (hours < 1) return "just now";
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  if (days === 1) return "yesterday";
  return `${days}d ago`;
}

export const LEVELS: JobLevel[] = ["Entry", "Experienced", "Supervisor"];
export const TYPES: JobType[] = ["Full-time", "Part-time", "Contract"];
export const MODES: WorkMode[] = ["On-site"];
